[package]
name = "meta-vote-contract"
version = "2.0.0"
edition = "2021"
authors = ["metapool.app <hello@metapool.app>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { version = "5.15.1", features = ["abi", "legacy"] }
near-contract-standards = "5.15.1"
uint = "0.9.3"
