[package]
name = "mpip-contract"
version = "0.1.3"
edition = "2021"
authors = ["Leandro Manzanal <leomanzanal@gmail.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5.15.1"
near-contract-standards = "5.15.1"
uint = "0.9.3"
