[package]
name = "kv-store-contract"
version = "1.0.0"
edition = "2021"
authors = ["metapool.app <hello@metapool.app>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.15.1"
near-contract-standards = "5.15.1"
uint = "0.9.3"
